---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zcashd-peers
spec:
  selector:
    matchLabels:
      app: zcashd-peers
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: zcashd-peers
    spec:
      serviceAccountName: zcashd-peers
      containers:
      - name: zcashd-peers
        image: doubtingben/zcashd-peers
        imagePullPolicy: Always
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: zcashd-peers
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zcashd-peers
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: zcashd-peers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zcashd-peers
subjects:
- kind: ServiceAccount
  name: zcashd-peers
  namespace: default
